name: Merge

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

env:
  RAILS_ENV: test
  RUBY_VERSION: '3.0.4'


jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: paulhatch/semantic-version@3d2ea28b25c9a892b07cd24b5675300b701fcef5
        id: semver
        with:
          # The prefix to use to identify tags
          branch: "main"
          # The prefix to use to identify tags
          tag_prefix: "v"
          # A string which, if present in a git commit, indicates that a change represents a
          # major (breaking) change, supports regular expressions wrapped with '/'
          major_pattern: "(MAJOR)"
          # Same as above except indicating a minor change, supports regular expressions wrapped with '/'
          minor_pattern: "(MINOR)"
          # A string to determine the format of the version output
          format: "${major}.${minor}.${patch}"
          # Optional path to check for changes. If any changes are detected in the path the
          # 'changed' output will true. Enter multiple paths separated by spaces.
          #change_path: "src/my-service"
          # Named version, will be used as suffix for name version tag
          # namespace: semver-demo
          # Indicate whether short tags like 'v1' should be supported. If false only full
          # tags like 'v1.0.0' will be recognized.
          # short_tags: true
          # If this is set to true, *every* commit will be treated as a new version.
          bump_each_commit: true

      # Sean 4/15 - disabling this for a manual tag cause it's broken: https://github.com/actions-ecosystem/action-push-tag/issues/10
#      - uses: actions-ecosystem/action-push-tag@6e82caefe706f5a729e354df7443dc82f98a414f
#        with:
#          tag: ${{ steps.semver.outputs.version }}
#          message: '${{ steps.semver.outputs.version }}: PR #${{ github.event.pull_request.number }} ${{ github.event.pull_request.title }}'


      - name: Tag
        run: |
          tag=${{ steps.semver.outputs.version }}
          message='${{ steps.semver.outputs.version }}: PR #${{ github.event.pull_request.number }} ${{ github.event.pull_request.title }}'
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git tag -a "${tag}" -m "${message}"
          git push origin "${tag}"